[build]
  publish = "public"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  included_files = ["data/**"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/verify/*"
  to = "/.netlify/functions/api/verify/:splat"
  status = 200

[[redirects]]
  from = "/v/*"
  to = "/.netlify/functions/api/v/:splat"
  status = 200